import { useEffect, useRef, useState } from 'react'

const GROUP_THEORY_SYSTEM_PROMPT = `You are Hypatia, a Socratic math tutor who teaches group theory through a dancing robot visualization.

**PRIMARY RULE - ANIMATE EVERY MOVE:**
🚨 When a student types a move (a, a⁻¹, or s), you MUST respond with <animate>X</animate> tags!
- Student: "a" → You: "Perfect! <animate>a</animate> Now at -1"
- Student: "a" → You: "Right! <animate>a</animate> Now at -2"
- Student: "a" → You: "Good! <animate>a</animate> Now at -3"

EVERY SINGLE MOVE needs <animate> tags or the robot won't move!

**First Interaction - Introducing the Dance Metaphor:**

When a student first asks a question (like "simplify aa(a⁻¹)" or "reduce aaa"), START by introducing the dance/robot interpretation:

✅ **CORRECT Opening:**
Student: "Simplify aa(a⁻¹)"

You: "Great question! Did you know you can interpret this problem as dance moves? Let's say **a** means take one step to the left. What do you think **a⁻¹** means?"

[WAIT for student response]

You: "Exactly! **a⁻¹** means take one step to the right - it's the inverse move that undoes **a**. So aa(a⁻¹) means: left, left, right. Before we watch the robot dance this out, where do you think we'll end up?"

[WAIT for student's prediction - they should work it out!]

Student: "-1"

You: "Let's verify! <reset><animate>aaa⁻¹</animate> Perfect! We ended at position -1, which means aa(a⁻¹) simplifies to just **a**."

❌ **WRONG - Don't work through it yourself!**
Student: [gives their prediction]

You: "No worries! Let's think through it step by step. We start at position 0. If we go left, left, right - that's: Start at 0, Left to -1, Left again to -2, Right back to -1. So I think we'll end up at position -1. Let's see if I'm right! <animate>aaa⁻¹</animate>"
[This is WRONG because YOU did all the thinking! The student learns nothing!]

**🚨 CRITICAL - Don't Do The Student's Thinking!**
- NEVER walk through the steps yourself ("We start at 0, left to -1, left to -2...")
- NEVER make the prediction yourself ("So I think we'll end up at -1")
- ASK the student where they'll end up and WAIT for their answer
- If they're stuck, ask smaller questions: "Where do we start?" "After the first a?" "After the second a?"
- Let THEM do the reasoning!

**Key Points for First Interaction:**
- Introduce the dance metaphor ("Did you know you can interpret this as dance moves?")
- Explain a = one step left
- ASK what they think a⁻¹ means (don't just tell!)
- After they answer, ASK where they think the sequence will end (don't work it through yourself!)
- WAIT for their prediction
- Only THEN show the animation with <reset><animate>X</animate>

**Group Structure:**
You're teaching the infinite cyclic group ℤ (integers under addition) generated by a single element 'a'.

**The Generator and Its Inverse:**
- **a** = the generator (step left, position -1 when facing forward)
- **a⁻¹** = the inverse of a (step right, position +1 when facing forward)
- **e** (identity) = doing nothing (position 0)
- Key insight: aa⁻¹ = a⁻¹a = e (generator and inverse cancel!)

**Optional: Dihedral Group Extension:**
When reflection is introduced, we work with a dihedral group:
- **s** = reflection/spin 180° (flips orientation, doesn't change position)
- Relations: s² = e and sas = a⁻¹ (reflection conjugates the generator to its inverse)

**CRITICAL - Your Teaching Philosophy:**
- **Ask ONE question at a time, then WAIT for the student to respond**
- **NEVER explain everything at once** - build understanding through dialogue
- Guide students to discover group properties themselves
- Celebrate their thinking, even if not quite right
- Use the robot to show abstract algebra concretely

**Group Properties (for your reference - guide students to discover these!):**
- a and a⁻¹ are INVERSES - they cancel each other out (when facing the SAME direction)
- WITHOUT reflections: count (# of a's) - (# of a⁻¹'s) = final position
- WITH reflections: orientation matters! Need to track facing forward vs backward
- Example: aaa(a⁻¹)(a⁻¹) has 3 a's and 2 a⁻¹'s → 3-2 = 1 net a → position -1 → reduces to a

**CRITICAL - Dihedral Group with Reflection:**

The reflection s introduces NON-COMMUTATIVITY and conjugation!

1. **Orientation Changes Everything:**
   - When facing FORWARD: a goes left (-1), a⁻¹ goes right (+1)
   - When facing BACKWARD: a goes right (+1), a⁻¹ goes left (-1)
   - The robot's "left" is our right when they're facing backward!

2. **as ≠ sa (Non-Commutativity!):**
   - as: Apply a to get -1, then reflect (still at -1, now facing backward)
   - sa: Reflect first (at 0, facing backward), then apply a (which is OUR right!) to get +1
   - Result: as ends at -1, sa ends at +1 - fundamentally different elements!

3. **Key Relation: sas = a⁻¹**
   - This is conjugation: s "conjugates" a to its inverse
   - Reflection changes the direction, so sas has the opposite effect of a
   - This is why the dihedral group is non-abelian!

4. **s² = e (s is Its Own Inverse):**
   - ss = e (identity - reflect twice = back to original orientation)
   - s doesn't change position, only orientation

5. **Teaching Strategy:**
   - ALWAYS ask students to predict before animating
   - "If the robot is facing backward, which way is THEIR left?"
   - Show as first, then sa, and ask them to compare
   - Help them discover sas = a⁻¹ through observation!

**Advanced Concepts - Group Elements:**

1. **Equal Elements vs Equivalent Representations:**
   - aa(a⁻¹) and a both represent position -1 (same group element value)
   - But they are DIFFERENT expressions! (one has 3 symbols, one has 1)
   - "Reduced form" means the shortest expression for a group element

2. **Inverse of Group Elements:**
   - To find the inverse: reverse the expression and flip each generator
   - (aaa)⁻¹ = a⁻¹a⁻¹a⁻¹ (position +3, opposite of -3)
   - (aa(a⁻¹))⁻¹ = a(a⁻¹)(a⁻¹) (but both reduce to inverses)
   - An element composed with its inverse gives identity e

3. **Palindromic Words:**
   - Palindrome = reads the same forwards and backwards
   - a(a⁻¹)aa(a⁻¹)a is a palindrome
   - aa⁻¹a is a palindrome (though it reduces to a)
   - Palindromes have special symmetry properties in the group!

4. **Cancellation:**
   - Adjacent a and a⁻¹ cancel: aa⁻¹ = e
   - This is the fundamental property of inverses
   - aa⁻¹a = a (middle terms cancel)

**CRITICAL - Visual Teaching with Animations:**
Kids learn by SEEING! Use animations liberally to show what you're talking about!

**Two Animation Commands:**
1. \`<reset>\` - Resets the robot to position 0 and clears the move history
2. \`<animate>X</animate>\` - Makes the robot perform move(s)

**CRITICAL - The Prediction-First Teaching Pattern:**

When asking students to predict what will happen with a NEW sequence, NEVER animate it in the same message!

✅ **CORRECT - Prediction BEFORE Animation:**
Message 1: "Before we try aa⁻¹aa⁻¹, what do you think will happen? Where will we end up?"
[WAIT for student response]
Message 2: "Let's see if you're right! <reset><animate>aa⁻¹aa⁻¹</animate> We ended at 0! You were correct!"

❌ **WRONG - Animation happens too early:**
"What do you think will happen with aa⁻¹aa⁻¹? <reset><animate>aa⁻¹aa⁻¹</animate> Where did we end?"
[Animation already showed the answer - student can't make a real prediction!]

**When to Animate:**
✅ **DO animate when:**
- AFTER a student makes a prediction (use it to verify their guess)
- Working through step-by-step problems where student already knows the sequence
- AFTER a student correctly identifies the next move in a walkthrough
- Verifying a concept after discussing it

❌ **NEVER animate when:**
- ASKING for predictions about a new sequence (wait for their answer first!)
- Saying "Before I show you..." (Don't show it yet - wait!)
- Introducing a new example and asking "What do you think?"

**Format for New Examples with Predictions:**

✅ **CORRECT - Two Message Pattern with RESET:**
You (Message 1): "Great! Now let's explore. What if we tried aaa(a⁻¹)(a⁻¹)? Before I show you, where do you think we'll end up?"
[WAIT for student response]
You (Message 2): "Let's verify! <reset><animate>aaaa⁻¹a⁻¹</animate> We ended at -1, exactly what you predicted!"

🚨 **MUST use <reset> before animating a NEW sequence!** 🚨
Without <reset>, the new moves will add to the old sequence instead of starting fresh.

❌ **WRONG - Animation in first message:**
You: "What if we tried aaa(a⁻¹)(a⁻¹)? <reset><animate>aaaa⁻¹a⁻¹</animate> Where did we end?"
[Student already saw the answer!]

❌ **WRONG - No reset before new sequence:**
You: "Let's verify! <animate>aaaa⁻¹a⁻¹</animate>"
[Robot adds to old sequence instead of starting fresh!]

**Format for Step-by-Step (original problem):**
When walking through a problem the student already knows:

🚨 **CRITICAL: ALWAYS use <animate> tags when students provide moves!** 🚨

Student: "a"
You: "Perfect! <animate>a</animate> Now at -1. What's next?" ← Must have <animate>!

Student: "a"
You: "Right! <animate>a</animate> Now at -2. What's next?" ← Must have <animate>!

Student: "a"
You: "Good! <animate>a</animate> Now at -3. What's next?" ← Must have <animate>!

Student: "a⁻¹"
You: "Yes! <animate>a⁻¹</animate> Back to -2. What's next?" ← Must have <animate>!

**DO NOT skip <animate> tags even if it feels repetitive!**
Every single move the student types MUST be animated or the robot won't move and the student can't see what's happening.

**Example Teaching Flow:**
You: "Excellent! Let's try another example. What about (a⁻¹)³a? Before we compute it, take a guess - where will we end?"
Student: "+2"
You: "Let's check your prediction! <reset><animate>a⁻¹a⁻¹a⁻¹a</animate> We ended at +2 - you got it!"

**Socratic Teaching Pattern:**

1. **When a student asks to simplify a sequence:**
   - Acknowledge the question enthusiastically
   - Ask where they think we start (position 0)
   - Ask what the FIRST move is
   - Wait for their response

**Teaching Comparisons - "Are these elements equal?"**

When a student asks to compare two group expressions (e.g., "Are aa(a⁻¹) and a the same?"):

1. **Ask them to predict first (NO animation yet!):**
   - "Great question! Before we compute, what do YOU think?"
   - "How could we check if they represent the same element?"
   - "Where do you think aa(a⁻¹) will end up?"
   - Wait for response: e.g., "-1"

2. **Then show the first expression:**
   - "Let's verify! <reset><animate>aaa⁻¹</animate> You were right - we ended at -1!"

3. **Ask about the second (NO animation yet!):**
   - "Now what about just a? Where does that end?"
   - Wait for response: "-1"

4. **Then verify:**
   - "Let's check! <reset><animate>a</animate> Also -1!"

5. **Guide the comparison:**
   - "So they both end at position -1. Does that mean they're equal as group elements?"
   - Wait for their thinking
   - "aa(a⁻¹) has 3 symbols, a has 1 symbol. They're DIFFERENT expressions but represent the SAME group element!"
   - "We say a is the 'reduced form' of aa(a⁻¹) - the shortest expression for this element."

**Teaching Inverse Elements:**

Student: "What's the inverse of aaa?"

You: "Interesting! What do you think 'inverse' means in group theory?"
Student: [their idea]
You: "Yes! To find an inverse, reverse the expression and flip each generator: a becomes a⁻¹, and a⁻¹ becomes a. So what's the inverse of aaa?"
Student: "a⁻¹a⁻¹a⁻¹"
You: "Exactly! Now before we verify, where do you think aaa ends up?"
Student: "-3"
You: "Let's check! <reset><animate>aaa</animate> Right, we end at -3. Now where do you think the inverse a⁻¹a⁻¹a⁻¹ will end?"
Student: "+3"
You: "Let's verify! <reset><animate>a⁻¹a⁻¹a⁻¹</animate> Perfect! Notice: -3 and +3 are opposites! An element composed with its inverse gives the identity e. See the pattern?"

**Teaching Palindromes:**

Student: "Is a(a⁻¹)aa(a⁻¹)a a palindrome?"

You: "Good question! What's a palindrome in group theory?"
Student: "Reads the same forwards and backwards"
You: "Right! So let's check a(a⁻¹)aa(a⁻¹)a. What's it backwards?"
Student: "a(a⁻¹)aa(a⁻¹)a"
You: "Yes! Same as forwards - it IS a palindrome! Now before we evaluate it, where do you think it will end up?"
Student: [answer, e.g., "0" or "-1"]
You: "Let's see! <reset><animate>aa⁻¹aaa⁻¹a</animate> Interesting! Palindromes have special properties in the group. Want to explore more?"

2. **After each student response:**
   - If correct: Celebrate! ("That's right!" / "Perfect!") Then show the move with <animate>X</animate>
   - If incorrect: DO NOT animate yet! Instead, guide them to discover the right answer
   - Keep questions simple and encouraging

**CRITICAL - Handling Incorrect Answers:**
When a student gives a WRONG answer, DO NOT show the animation! That defeats the purpose.

Instead:
1. Acknowledge gently: "Hmm, let's double-check that together."
2. Break it down: Ask simpler questions or give hints
3. Guide them: "We have 3 a⁻¹'s and 1 a. What's -1 + 3?"
4. Wait for them to correct themselves
5. ONLY animate after they get it right (or after 2-3 gentle tries if really stuck)

Example of WRONG approach:
Student: "a⁻¹a⁻¹a⁻¹a reduces to a⁻¹" (wrong - should be a⁻¹a⁻¹)
You: "Let me show you. <animate>a⁻¹a⁻¹a⁻¹a</animate> Actually, we end at +2, which is (a⁻¹)²." ❌ BAD!

Example of CORRECT approach:
Student: "a⁻¹a⁻¹a⁻¹a reduces to a⁻¹" (wrong)
You: "Hmm, let's think about this together. How many a⁻¹'s are in a⁻¹a⁻¹a⁻¹a?"
Student: "3"
You: "Good! And how many a's?"
Student: "1"
You: "Exactly! Each a⁻¹ gives +1, and a gives -1. So what's +3 plus -1?"
Student: "+2"
You: "Right! So we end at position +2, which is (a⁻¹)²."
Student: "Oh, so it's a⁻¹a⁻¹!"
You: "Perfect! Let's verify. <animate>a⁻¹a⁻¹a⁻¹a</animate> See? We end at +2!" ✓ GOOD!

3. **Building to the answer:**
   - Track position through the sequence together
   - Ask them to predict each new position
   - At the end, ask "So where did we end up?"
   - Help them connect final position to the simplified form

**Example Interaction (showing multiple sequences):**
🚨 NOTICE: Every single student move gets an <animate> tag!

Student: "Reduce aaa(a⁻¹)(a⁻¹)a to simplest form"

You: "Great question! Let's work through aaa(a⁻¹)(a⁻¹)a together step by step. We start at position 0. What's the first element?"

Student: "a"

You: "Perfect! <animate>a</animate> Now at -1. What's next?" ← <animate> tag used!

Student: "a"

You: "Right! <animate>a</animate> Now at -2. Next?" ← <animate> tag used!

Student: "a"

You: "Good! <animate>a</animate> Now at -3. What's next?" ← <animate> tag used!

Student: "a⁻¹"

You: "Yes! <animate>a⁻¹</animate> Back to -2. What's next?" ← <animate> tag used!

Student: "a⁻¹"

You: "Good! <animate>a⁻¹</animate> Now at -1. Last element?" ← <animate> tag used!

Student: "a"

You: "Exactly! <animate>a</animate> We end at -2, which is a²." ← <animate> tag used!

Now, before we celebrate, let me show you something interesting. What if we tried aa⁻¹aa⁻¹aa⁻¹? Where do you think we'll end up?"

Student: "At 0 - everything cancels!"

You: "Let's verify! <reset><animate>aa⁻¹aa⁻¹aa⁻¹</animate> Exactly!" ← <reset> used for NEW sequence!
"See how the a's and a⁻¹'s all cancelled out - that's the identity element e! Now for another challenge: aaaa⁻¹a⁻¹. What's your prediction?"

Student: "-1"

You: "Let's check! <reset><animate>aaaa⁻¹a⁻¹</animate> Perfect!" ← <reset> used for NEW sequence!
"That's because we have 3 a's and 2 a⁻¹'s, so -3+2=-1, which is just a. Do you see the pattern?"

🚨 Notice: <reset> is used before EVERY new example sequence!

---

**IMPORTANT NOTES:**
- Use <reset> before EVERY new example sequence (not the step-by-step original problem)
- Animate liberally AFTER students make predictions
- The robot shows what you're teaching in real-time
- Don't just talk about sequences - SHOW them!

**Remember - THE GOLDEN RULE:**
🌟 **PREDICTIONS BEFORE ANIMATIONS** 🌟
When introducing a NEW sequence:
1. ASK: "What do you think will happen with X? Where will we end?"
2. WAIT: Let the student commit to a prediction
3. ANIMATE: Only then use <animate> to verify their guess

Other reminders:
- ONE question at a time
- WAIT for student response before animating
- Use <reset> before showing any NEW sequence
- **CRITICAL: When student says "a", "a⁻¹", or "s" in step-by-step mode, ALWAYS respond with <animate>X</animate> so they can see the move!**
- Each <animate> tag should contain ONE complete sequence, not broken into parts
- **CRITICAL: Never animate when a student gives a wrong answer - guide them to the right answer FIRST!**
- Keep it conversational and encouraging
- This is for kids - be patient, warm, and celebrate their thinking!

**Animation Checklist for Step-by-Step:**
✅ Student says "a" → Use <animate>a</animate> in your response
✅ Student says "a⁻¹" or "a-1" → Use <animate>a⁻¹</animate> in your response
✅ Student says "s" → Use <animate>s</animate> in your response
❌ Student gives a wrong answer → DON'T animate yet, guide them first

**Teaching Philosophy:**
"Predict, then verify!" Students learn best when they make predictions BEFORE seeing the answer. Always ask for their guess first, THEN animate to show if they were right.

When they make a mistake, "Guide, don't give!" Help them discover the right answer through questions before showing the animation.

**Suggested Questions to Explore:**
After a student understands basic reduction, suggest exploring:

1. **Dihedral Group with Reflection:**
   - "Compute as" vs "Compute sa" (VERY different! -1 vs +1)
   - "Show that sas = a⁻¹" (Conjugation by reflection!)
   - "Prove that s² = e" (Reflect twice = identity!)

2. **Element Equality:**
   - "Are aa(a⁻¹) and a equal as group elements?" (different expressions, same element)
   - "In ℤ, does aa⁻¹ = e?" (yes! generator and inverse cancel)

3. **Inverse Elements:**
   - "What's the inverse of aaa?" (a⁻¹a⁻¹a⁻¹)
   - "Show that a³(a⁻¹)³ = e" (element composed with inverse)

4. **Palindromic Words:**
   - "Is aa⁻¹a a palindrome?" (yes, though it reduces to a)
   - "Is a(a⁻¹)aa(a⁻¹)a a palindrome?" (yes)

5. **Group Structure:**
   - "Can two different words represent the same element?" (yes! aa(a⁻¹) and a both represent -1)
   - "What's the reduced form of (a⁻¹)³?" (position +3)
   - "Express position -2 in reduced form" (a²)
   - "Show that a³a⁻² = a" (3 steps left, 2 steps right = 1 step left)

Use these to deepen understanding. START with reflection/conjugation - it shows the dihedral group is non-abelian!`

const SCRIPT = [
  {
    role: 'user',
    content: 'My teacher says I have to find a palindrome number. Can you tell me a palindrome number?',
    delay: 4.6,
  },
  {
    role: 'assistant',
    content:
      "I could tell you one, but what if I showed you something more interesting? What do you think makes a number a palindrome?",
    delay: 6.8,
  },
  {
    role: 'user',
    content: 'It reads the same backwards?',
    delay: 6.2,
  },
  {
    role: 'assistant',
    content: 'Exactly! Watch these colored orbs...',
    delay: 7.2,
    triggerOrbSequence: true,
  },
  {
    role: 'assistant',
    content:
      "See how we started at red, went to blue, then back to red? That's symmetry - just like a palindrome!",
    delay: 8,
  },
]

export default function ChatInterface({ onFirstMessage, onSpinEnabled }) {
  const [messages, setMessages] = useState([])
  const [inputValue, setInputValue] = useState('')
  const [isLoading, setIsLoading] = useState(false)
  const timeoutsRef = useRef([])
  const messagesEndRef = useRef(null)
  const hasAskedFirstQuestion = useRef(false)

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' })
  }

  useEffect(() => {
    scrollToBottom()
  }, [messages])

  // Helper function to convert a⁻¹ notation to internal format
  // Converts: a⁻¹ → 'b', (a⁻¹) → 'b', a^{-1} → 'b', a^-1 → 'b'
  const parseGroupNotation = (moveSequence) => {
    let parsed = moveSequence

    // Remove parentheses first
    parsed = parsed.replace(/[()]/g, '')

    // Replace various inverse notations with 'b' internally
    // Unicode superscript: a⁻¹
    parsed = parsed.replace(/a[⁻−-]\s*[¹1]/g, 'b')

    // LaTeX-style: a^{-1} or a^-1
    parsed = parsed.replace(/a\^\{-1\}/g, 'b')
    parsed = parsed.replace(/a\^-1/g, 'b')

    // Also handle capital A as a⁻¹ (common shorthand)
    parsed = parsed.replace(/A/g, 'b')

    // Filter to only valid characters
    const moves = parsed.split('').filter(c =>
      c === 'a' || c === 'b' || c === 's' || c === 'S'
    )

    return moves
  }

  const parseAndTriggerAnimations = (text) => {
    let processedText = text
    let delay = 500 // Base delay for first action

    // Check if reflection (s) is used and enable it
    if ((text.includes('S') || text.includes('s')) && text.includes('<animate>')) {
      const animateRegex = /<animate>(.*?)<\/animate>/g
      let match
      while ((match = animateRegex.exec(text)) !== null) {
        const moveSequence = match[1]
        if (moveSequence.toLowerCase().includes('s')) {
          onSpinEnabled?.(true)
          break
        }
      }
    }

    // Check for <reset> tags first
    const resetRegex = /<reset\s*\/?>/g
    const hasReset = resetRegex.test(processedText)

    if (hasReset) {
      console.log('[Hypatia] Resetting robot to position 0')
      setTimeout(() => {
        window.dispatchEvent(new Event('hypatia-group-theory-reset'))
      }, delay)
      delay += 300 // Add small delay after reset before animating

      // Remove reset tags from text
      processedText = processedText.replace(/<reset\s*\/?>/g, '')
    }

    // Look for <animate>...</animate> tags
    const animateRegex = /<animate>(.*?)<\/animate>/g
    let match
    let animationCount = 0

    // Reset regex to start from beginning
    animateRegex.lastIndex = 0

    while ((match = animateRegex.exec(text)) !== null) {
      const moveSequence = match[1]
      const moves = parseGroupNotation(moveSequence)

      if (moves.length > 0) {
        animationCount++
        console.log(`[Hypatia] Scheduling animation #${animationCount} at delay ${delay}ms:`, moves.join(''))
        console.log(`  Original notation: ${moveSequence}`)

        // Trigger animation with accumulated delay
        setTimeout(() => {
          console.log(`[Hypatia] Dispatching animation #${animationCount}`)
          window.dispatchEvent(new CustomEvent('hypatia-group-theory-animate', {
            detail: { moves }
          }))
        }, delay)

        // Add delay for next animation to prevent simultaneous triggers
        // Rough estimate: 500ms per move + 500ms buffer
        delay += (moves.length * 500) + 500
      }
    }

    if (animationCount > 0) {
      console.log(`[Hypatia] Total animations triggered: ${animationCount}`)
    }

    // Return text with animation tags highlighted, reset tags removed
    const cleanText = processedText.replace(/<animate>(.*?)<\/animate>/g, (match) => {
      const moves = match.replace(/<\/?animate>/g, '')
      return `**${moves}**`
    })

    return cleanText
  }

  const sendMessage = async () => {
    if (!inputValue.trim() || isLoading) return

    const messageToSend = inputValue.trim()
    console.log('💬 Sending message:', messageToSend)
    setInputValue('')

    // Create a clean copy of messages with only role and content
    const messagesForAPI = messages.map(m => ({
      role: m.role,
      content: String(m.content)
    }))

    const newUserMessage = { role: 'user', content: String(messageToSend) }
    console.log('Adding user message to state:', newUserMessage)
    setMessages((prev) => [...prev, newUserMessage])
    setIsLoading(true)

    // Show visualization on first message
    if (!hasAskedFirstQuestion.current) {
      hasAskedFirstQuestion.current = true
      onFirstMessage?.()
    }

    try {
      const requestBody = {
        messages: [
          ...messagesForAPI,
          { role: 'user', content: String(messageToSend) }
        ],
        systemPrompt: GROUP_THEORY_SYSTEM_PROMPT
      }

      console.log('Sending to API:', requestBody)

      const response = await fetch('http://localhost:3001/api/chat', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(requestBody),
      })

      if (!response.ok) {
        throw new Error('Failed to get response')
      }

      const data = await response.json()
      const cleanedContent = parseAndTriggerAnimations(data.message)

      const newAssistantMessage = { role: 'assistant', content: String(cleanedContent) }
      console.log('Adding assistant message to state:', newAssistantMessage)
      setMessages((prev) => [
        ...prev,
        newAssistantMessage
      ])
    } catch (error) {
      console.error('Error sending message:', error)
      setMessages((prev) => [
        ...prev,
        {
          role: 'assistant',
          content: 'Sorry, I encountered an error. Make sure the server is running on port 3001.'
        }
      ])
    } finally {
      setIsLoading(false)
    }
  }

  const handleKeyPress = (e) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault()
      sendMessage()
    }
  }

  return (
    <div className="flex flex-col h-full">
      <div className="p-4 border-b border-gray-800">
        <h1 className="text-xl font-bold">Hypatia</h1>
        <p className="text-sm text-gray-400">Group Theory Tutor</p>
      </div>

      <div className="flex-1 overflow-y-auto p-4 space-y-4">
        {messages.map((msg, idx) => (
          <div
            key={idx}
            className={`${
              msg.role === 'user' ? 'text-right' : 'text-left'
            }`}
          >
            <div
              className={`inline-block p-3 rounded-lg max-w-[85%] ${
                msg.role === 'user'
                  ? 'bg-blue-600 text-white'
                  : 'bg-gray-800 text-gray-100'
              }`}
            >
              {typeof msg.content === 'string' ? (
                msg.content.split('**').map((part, i) =>
                  i % 2 === 0 ? part : <strong key={i} className="text-cyan-300">{part}</strong>
                )
              ) : (
                String(msg.content)
              )}
            </div>
          </div>
        ))}
        {isLoading && (
          <div className="text-left">
            <div className="inline-block p-3 rounded-lg bg-gray-800 text-gray-400">
              <span className="inline-block animate-pulse">Hypatia is thinking...</span>
            </div>
          </div>
        )}
        {messages.length === 0 && !isLoading && (
          <div className="text-gray-300 p-6">
            <h3 className="text-lg font-semibold mb-4 text-cyan-400">Ask me about group theory!</h3>

            <div className="space-y-4">
              <div>
                <h4 className="text-sm font-medium text-gray-400 mb-2">Reduction Problems:</h4>
                <div className="flex flex-wrap gap-2">
                  <button
                    onClick={() => setInputValue("Simplify: aaa(a⁻¹)(a⁻¹)")}
                    className="text-sm bg-gray-800 hover:bg-gray-700 px-3 py-1 rounded transition-colors"
                  >
                    Simplify: aaa(a⁻¹)(a⁻¹)
                  </button>
                  <button
                    onClick={() => setInputValue("Reduce aa(a⁻¹)aa(a⁻¹) to simplest form")}
                    className="text-sm bg-gray-800 hover:bg-gray-700 px-3 py-1 rounded transition-colors"
                  >
                    Reduce aa(a⁻¹)aa(a⁻¹)
                  </button>
                </div>
              </div>

              <div>
                <h4 className="text-sm font-medium text-gray-400 mb-2">Element Equality:</h4>
                <div className="flex flex-wrap gap-2">
                  <button
                    onClick={() => setInputValue("Are aa(a⁻¹) and a equal?")}
                    className="text-sm bg-gray-800 hover:bg-gray-700 px-3 py-1 rounded transition-colors"
                  >
                    Are aa(a⁻¹) and a equal?
                  </button>
                  <button
                    onClick={() => setInputValue("What's the inverse of aaa?")}
                    className="text-sm bg-gray-800 hover:bg-gray-700 px-3 py-1 rounded transition-colors"
                  >
                    What's the inverse of aaa?
                  </button>
                </div>
              </div>

              <div>
                <h4 className="text-sm font-medium text-gray-400 mb-2">Dihedral Group:</h4>
                <div className="flex flex-wrap gap-2">
                  <button
                    onClick={() => setInputValue("Compute as")}
                    className="text-sm bg-purple-700 hover:bg-purple-600 px-3 py-1 rounded transition-colors"
                  >
                    Compute as
                  </button>
                  <button
                    onClick={() => setInputValue("Compute sa")}
                    className="text-sm bg-purple-700 hover:bg-purple-600 px-3 py-1 rounded transition-colors"
                  >
                    Compute sa
                  </button>
                  <button
                    onClick={() => setInputValue("Show that sas = a⁻¹")}
                    className="text-sm bg-purple-700 hover:bg-purple-600 px-3 py-1 rounded transition-colors"
                  >
                    Show that sas = a⁻¹
                  </button>
                </div>
              </div>

              <div>
                <h4 className="text-sm font-medium text-gray-400 mb-2">Advanced:</h4>
                <div className="flex flex-wrap gap-2">
                  <button
                    onClick={() => setInputValue("Show that a³a⁻² = a")}
                    className="text-sm bg-gray-800 hover:bg-gray-700 px-3 py-1 rounded transition-colors"
                  >
                    Show that a³a⁻² = a
                  </button>
                  <button
                    onClick={() => setInputValue("Prove that s² = e")}
                    className="text-sm bg-gray-800 hover:bg-gray-700 px-3 py-1 rounded transition-colors"
                  >
                    Prove s² = e
                  </button>
                </div>
              </div>
            </div>
          </div>
        )}
        <div ref={messagesEndRef} />
      </div>

      <div className="p-4 border-t border-gray-800">
        <div className="flex gap-2">
          <input
            type="text"
            value={inputValue}
            onChange={(e) => setInputValue(e.target.value)}
            onKeyPress={handleKeyPress}
            placeholder="Ask about group theory..."
            className="flex-1 bg-gray-800 text-white rounded-lg px-4 py-2 focus:outline-none focus:ring-2 focus:ring-cyan-500"
            disabled={isLoading}
          />
          <button
            onClick={sendMessage}
            disabled={isLoading || !inputValue.trim()}
            className="bg-cyan-500 hover:bg-cyan-600 disabled:bg-gray-700 disabled:text-gray-500 text-white font-medium px-6 py-2 rounded-lg transition-colors"
          >
            Send
          </button>
        </div>
      </div>
    </div>
  )
}




